### PR TITLE
Fix issue with WATCH construct while executing on GPU

### PR DESCRIPTION
**Pull request by pramodk**
WATCH statement implementation accesses send buffer as:

    _ml->_net_send_buffer

but _ml is not specified in the present clause of _PRAGMA_FOR_STATE_ACC_LOOP_.
Added _ml to the present clause of _PRAGMA_FOR_STATE_ACC_LOOP_.

### CODE REVIEW

**Review by nrnhines — COMMENTED** [review]
Is there any downside in adding to the STATE_ACC_LOOP when the state block does not need that present item. I.e not worth defineing a _PRAGMA_FOR_WATCH_ACC_LOOP_ ?

**Comment by pramodk** [comment]
> Is there any downside in adding to the STATE_ACC_LOOP when the state block does not need that present item.

We access all variables using *_p* and *_ppvar* (without accessing via *_ml*). Hence it wasn't added to the present clause. there is no downside.

> I.e not worth defineing a PRAGMA_FOR_WATCH_ACC_LOOP ?

It would be clearer to have separate pragma. I will push the new change before merging this to master.

**Comment by nrnhines** [comment]
Sorry. I jumped the gun and merged as is.

________________________________________

**Comment by pramodk** [comment]
thats fine, we haven't merged with master yet.

**Pull request merged**
